# Use an official Node runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Bundle app source
COPY . .

# Build app for production
RUN npm run build

# Install a simple http server for serving static content
RUN npm install -g http-server

# Serve the app
CMD ["http-server", "dist", "-P", "http://localhost:8080?"]